name: Build Sphinx Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk
        pip install sphinx
        pip install sphinx_rtd_theme  # Om du använder ett specifikt tema
    - name: Generate ReStructuredText files
      run: |
        sphinx-apidoc -o docs/source ../src/
    - name: Build Text Documentation
      run: sphinx-build -b text docs/source docs/build/text
    - name: Deploy Text Documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/text
